name: Pull request

on:
  pull_request:
    branches:
      - chore/setup-test

jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit convention
        run: |
          yarn add @commitlint/cli @commitlint/config-conventional -D
          yarn commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  check-files-changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check files changed
        run: |
          if [ ${{ github.event.pull_request.changed_files }} -gt 10 ]; then
            echo "Too many files changed. One PR should only change <= 10 files."
            exit 1
          fi
