name: Unit test

on:
  push:
    branches:
      - chore/setup-test # Change this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change this to your desired Node.js version
          # cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Jest tests
        run: yarn test
